name: Automating Login

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your desired Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add any additional dependencies if required
        pip install pytest-html

    - name: Run Tests and Generate HTML Report
      run: |
        pytest --html=report.html testCases/test_login.py
        pytest --html=report.html testCases/test_register.py
        pytest --html=report.html testCases/test_search.py
      continue-on-error: true

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: report.html